---
- hosts: "controlplanes"
  become: yes
  tasks:
  - name: Resetting kubeadm
    shell: "[[ $(which kubeadm) ]] && sudo kubeadm reset -f || echo kubeadm_not_installed "
    register: output
    
  - name: Print output of kubeadm reset -f
    debug:
      msg: " => {{ output }}"

  - name: Resetting flannel and cni
    shell: |
     [[ -d /var/lib/cni     ]] && rm -rf /var/lib/cni/ 
     [[ -d /var/lib/kubelet ]] && rm -rf /var/lib/kubelet/* 
     [[ -d /etc/cni         ]] && rm -rf /etc/cni/ 
     [[ $(ip link show | grep flannel.1) ]] && ip link del flannel.1 || echo **************** no_flannel.1
     [[ $(ip link show | grep docker0) ]] && ip link del docker0 || echo **************** no_docker0
     [[ $(ip link show | grep cni0) ]] && ip link del cni0 || echo **************** no_cni0
     iptables -F

    register: output

  - name: Print output of Resetting flannel and cni
    debug:
      msg: " => {{ output }}"