name: buildcluster

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2
    - name: call python http server...to runnnnn 1 2 3 3 4 5 6 7
      run: |
        apt-get install -y iproute2
        curl -X POST $(ip route show | grep default | awk '{print $3}'):8080 -H "Content-Type: application/json Content-Length: 15" -d '{"foo": "bar"}'
     
