name: buildcluster

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2
    - name: call python http server to run the command
      run: |
        curl -X POST $(ip route show | grep default | awk '{print $3}'):8080 -H "Content-Type: application/json Content-Length: 15" -d '{"foo": "bar"}'
        ls -l /tmp/runner/work/k8s_ansible_ubuntu
