name: testRun

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2
    - name: test echo
      run: |
        echo "hello"
        ls -l 
        

